# https://taskfile.dev

version: "3"

tasks:
  build-img-n:
    cmds:
      - git pull
      - ./img-gen-n.sh

  build-img-s:
    cmds:
      - git pull
      - ./img-gen-s.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/p3/system/