# https://taskfile.dev

version: "3"

tasks:
  build-ext:
    cmds:
      - git reset --hard
      - git pull
      - ./img-ext.sh

  build-min:
    cmds:
      - git reset --hard
      - git pull
      - ./img-min.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/p3/system/