# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - git reset --hard
      - git pull
      - ./img-gen.sh
  build-local:
    cmds:
      - git reset --hard
      - git pull
      - ./img-gen.sh local