# https://taskfile.dev

version: '3'

tasks:
  build-img:
    cmds:
      - ./img-gen.sh

  build-docker-img:
    dir: docker
    cmds:
      - ./build.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/board/arpl/overlayfs/opt/arpl/
