# https://taskfile.dev

version: "3"

tasks:
  build-img:
    cmds:
      - git pull
      - ./img-gen.sh

tasks:
  build-img2:
    cmds:
      - git pull
      - ./img-gen2.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/board/arc/overlayfs/opt/arc/