id: "DS1019+"
synoinfo: &synoinfo
  support_disk_compatibility: "no"
  support_memory_compatibility: "no"
  support_bde_internal_10g: "no"
  support_led_brightness_adjustment: "no"
  support_leds_lp3943: ""
  support_oob_ctl: "no"
  support_syno_hybrid_raid:
  supportraidgroup:
  supportnvme: "yes"
  support_m2_pool: "yes"
  maxlanport: "8"
  netif_seq: "0 1 2 3 4 5 6 7"
  buzzeroffen: "0xffff"
  esataportcfg: "0x00"
cmdline: &cmdline
  HddHotplug: 0
  syno_hdd_detect: 0
  syno_hdd_powerup_seq: 0
  vender_format_version: 2
  elevator: elevator
platform: "apollolake"
unique: "synology_apollolake_1019+"
serial:
  prefix:
    - "1850"
  middle: "QXR"
  suffix: "numeric"
arc:
  serial: "1880QXRTXWRXT"
  mac1: "00113295B399"
  mac2: "00113295B39A"
dom: 2
disks: 5
dt: false
beta: false
flags:
  - "movbe"
builds:
  42962:
    ver: "7.1.1"
    kver: "4.4.180"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "42962-1"
    patch:
      - "ramdisk-common-disable-root-pwd.patch"
      - "ramdisk-common-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"
      - "ramdisk-42661-disable-disabled-ports.patch"

  64570:
    ver: "7.2"
    kver: "4.4.302"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "64570-1"
    patch:
      - "ramdisk-64216-disable-root-pwd.patch"
      - "ramdisk-64216-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"
      - "ramdisk-42661-disable-disabled-ports.patch"
