id: "FS2500"
synoinfo: &synoinfo
  support_disk_compatibility: "no"
  support_memory_compatibility: "no"
  support_led_brightness_adjustment: "no"
  support_syno_hybrid_raid:
  supportraidgroup:
  maxlanport: "8"
  netif_seq: "0 1 2 3 4 5 6 7"
cmdline: &cmdline
  intel_iommu: "igfx_off"
  synoboot2:
  SMBusHddDynamicPower: 1
  vender_format_version: 2
  syno_ttyS0: "serial,0x3f8"
  syno_ttyS1: "serial,0x2f8"
  elevator: elevator
platform: "v1000"
unique: "synology_v1000_fs2500"
serial:
  prefix:
    - "1960"
  middle: "PSN"
  suffix: "numeric"
dom: 2
dt: true
disks: 12
beta: true
builds:
  42962:
    ver: "7.1.1"
    kver: "4.4.180"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "42962-1"
    patch:
      - "ramdisk-common-disable-root-pwd.patch"
      - "ramdisk-common-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"

  64570:
    ver: "7.2.0"
    kver: "4.4.302"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "64570-1"
    patch:
      - "ramdisk-64216-disable-root-pwd.patch"
      - "ramdisk-64216-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"