id: "RS1221+"
synoinfo: &synoinfo
  support_disk_compatibility: "no"
  support_memory_compatibility: "no"
  support_bde_internal_10g: "no"
  support_led_brightness_adjustment: "no"
  support_oob_ctl: "no"
  support_syno_hybrid_raid:
  supportraidgroup:
  supportnvme: "yes"
  support_m2_pool: "yes"
  maxlanport: "8"
  netif_seq: "0 1 2 3 4 5 6 7"
cmdline: &cmdline
  HddHotplug: 0
  synoboot2:
  syno_hdd_detect: 0
  syno_hdd_powerup_seq: 0
  SMBusHddDynamicPower: 1
  vender_format_version: 2
  syno_ttyS0: "serial,0x3f8"
  syno_ttyS1: "serial,0x2f8"
  elevator: elevator
platform: "v1000"
unique: "synology_v1000_rs1221+"
serial:
  prefix:
    - "20B0"
  middle: "RWR"
  suffix: "alpha"
arc:
  serial: "20B0RWRQTT11P"
  mac1: "001132E2529A"
  mac2: "001132E2529B"
  mac3: "001132E2529C"
  mac4: "001132E2529D"
dom: 2
disks: 8
dt: true
beta: true
builds:
  42962:
    ver: "7.1.1"
    kver: "4.4.180"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "42962-1"
    patch:
      - "ramdisk-common-disable-root-pwd.patch"
      - "ramdisk-common-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"

  64570:
    ver: "7.2"
    kver: "4.4.302"
    rd-compressed: false
    cmdline:
      <<: *cmdline
    synoinfo:
      <<: *synoinfo
    dsm: "64570-1"
    patch:
      - "ramdisk-64216-disable-root-pwd.patch"
      - "ramdisk-64216-init-script.patch"
      - "ramdisk-common-etc-rc.patch"
      - "ramdisk-42951-post-init-script.patch"
