
ARC_VERSION="23.1.1"
ARC_TITLE="Arc ${ARC_VERSION}"

# Define paths
BOOTLOADER_PATH="/mnt/p1"
SLPART_PATH="/mnt/p2"
CACHE_PATH="/mnt/p3"
DSMROOT_PATH="/mnt/dsmroot"
TMP_PATH="/tmp"

UNTAR_PAT_PATH="${TMP_PATH}/DSM"
RAMDISK_PATH="${TMP_PATH}/ramdisk"
LOG_FILE="${TMP_PATH}/log.txt"

USER_CONFIG_FILE="${BOOTLOADER_PATH}/user-config.yml"
GRUB_PATH="${BOOTLOADER_PATH}/boot/grub"

ORI_ZIMAGE_FILE="${SLPART_PATH}/zImage"
ORI_RDGZ_FILE="${SLPART_PATH}/rd.gz"

ARC_BZIMAGE_FILE="${CACHE_PATH}/bzImage-arc"
ARC_RAMDISK_FILE="${CACHE_PATH}/initrd-arc"
MOD_ZIMAGE_FILE="${CACHE_PATH}/zImage-dsm"
MOD_RDGZ_FILE="${CACHE_PATH}/initrd-dsm"

ADDONS_PATH="${CACHE_PATH}/addons"
EXTENSIONS_PATH="${CACHE_PATH}/extensions"
MODULES_PATH="${CACHE_PATH}/modules"
MODEL_CONFIG_PATH="${CACHE_PATH}/configs"
PATCH_PATH="${CACHE_PATH}/patches"
LKM_PATH="${CACHE_PATH}/lkms"
USER_UP_PATH="${CACHE_PATH}/users"
BACKUPDIR="${CACHE_PATH}/backup"
BB_USER_CONFIG_FILE="${BACKUPDIR}/user-config.yml"

EXTRACTOR_PATH="${CACHE_PATH}/extractor"
EXTRACTOR_BIN="syno_extract_system_patch"