#
# Copyright (C) 2023 AuxXxilium <https://github.com/AuxXxilium>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: New version
on:
  workflow_dispatch:
    inputs:
        push: 
            description: 'push'
            default: true
            type: boolean
        version: 
            description: 'update version'
            default: false
            type: boolean
        buildold:
            description: '64551'
            required: true
            type: string
        buildnew:
            description: '64561'
            required: true
            type: string
        versionold:
            description: '7.2'
            required: false
            type: string
        versionnew:
            description: '7.2.1'
            required: false
            type: string
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace Build
        uses: jacobtomlinson/gha-find-replace@v3
        with:
            find: "${{ inputs.buildold }}"
            replace: "${{ inputs.buildnew }}"
            include: "files/board/arpl/mnt/p3/configs/**"
            regex: true
      
      - name: Replace Version
        if: inputs.version == true
        uses: jacobtomlinson/gha-find-replace@v3
        with:
            find: "${{ inputs.versionold }}"
            replace: "${{ inputs.versionnew }}"
            include: "files/board/arpl/mnt/p3/configs/**"
            regex: true

      # Install dependencies
      - name: Install dependencies
        if: inputs.push == true
        run: |
            git config --global user.email "info@auxxxilium.tech"
            git config --global user.name "AuxXxilium"
            sudo timedatectl set-timezone "Europe/Berlin"
      
      # Push to github
      - name: Push
        if: inputs.push == true
        run: |
            git pull
            status=$(git status -s | awk '{printf " %s", $2}')
            if [ -n "${status}" ]; then
                git add ${status}
                git commit -m "arc: update from ${{ inputs.buildold }} to ${{ inputs.buildnew }}"
                git push -f
            fi